### ISSUE TITLE
Implement endpoints for quizes

### ISSUE THREAD

**Issue by DeftCode-IT** [DeftCode-IT/Quiz-Designer#18]
Zaimplementować endpoint `GET /api/quizes/:id`.
Sprawa jest o tyle skomplikowana, że:
A. Wszystkie quizy ze statusem `published` są public.
B. Wszystkie quizy ze statusem `unpublished` i `archived` są protected i dostępne tylko dla autora quizu.

Zaimplementować endpoint `PATCH /api/quizes/:id`.
Zaimplementować endpoint `POST /api/quizes`
Zaimplementować endpoint `GET /api/quizes`
Wszystkie trzy powyższe są protected.

**Comment by MatexQ** [comment]
@DeftCode-IT czyli jeżeli user jest zalogowany i posiada swoje quizy to odpytując `GET /api/quizes/` dostaje quizy publiczne oraz własne? To ma być podzielona opcja np. 
```
data: {
   public: {
   ...
   },
   own: {
   ...
   }
}
```
czy jak to widzisz?

**Comment by DeftCode-IT** [comment]
Pobrać może zawsze tylko i wyłącznie swoje quizy, tak sami edytować, inaktywować itd.
Tylko w przypadku pojedynczego, opublikowanego quizu możesz mieć dostęp do quizu kogoś innego (jako osoba wypełniająca).

**Comment by DeftCode-IT** [comment]
Note: Każdy endpoint powinien mieć zaimplementowaną paginacje po stronie serwera a także w odpowiedzi zwracać też całkowitą ilość pozycji czyli:
```
data: tutaj_dane,
totalCount: ilosc_wszystkich_obiektów,
page: obecna_strona,
pageSize: wielkosc_strony
```
